### ISSUE TITLE
Documentation does not render with current Docker image due to sphinxcontrib.googlechart

### ISSUE THREAD

**Issue by sypets** [xperseguers/t3ext-sphinx#9]
"Could not import extension sphinxcontrib.googlechart"

```
cat tmp-GENERATED-temp/RenderDocumentation/2019-05-19_06-37-50_072139/18-Make-and-build/40-Html/xeq-40-Make-html-1-err.txt

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python2.7/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxcontrib.googlechart (exception: cannot import name Directive)

Extension error:
Could not import extension sphinxcontrib.googlechart (exception: cannot import name Directive)

```

Docker image: https://github.com/t3docs/docker-render-documentation

**Comment by sypets** [comment]
There is already a similar issue for the Docker image: https://github.com/t3docs/docker-render-documentation/issues/18

**Comment by xperseguers** [comment]
Not sure if the corresponding related issue says that it's been fixed and is working now or not. Easiest way would be to drop this extension as I suppose that by now it's very rarely used, if used at all, and I suspect it could now require a usage token just as Google Maps (or it could come anytime and will certainly not be adapted).
